// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { AOSInit } from "../src/AOSInit";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}<AOSInit /></body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import localFont from "next/font/local"; // Import modul font lokal
import "./globals.css";
import { AOSInit } from "../src/AOSInit";

const anginSenja = localFont({
  src: "../public/assets/fonts/Angin-Senja.otf", // Sesuaikan path relative dari file layout.tsx ke file font Anda
  variable: "--font-angin-senja", // Definisikan sebagai variabel CSS
});

export const metadata: Metadata = {
  title: "Youvitation",
  description: "Wedding Invitation",
  icons: {
    icon: "/logo.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`h-full flex flex-col ${anginSenja.variable} antialiased`}>
        {children}
        <AOSInit />
      </body>
    </html>
  );
}
